language: node_js
node_js:
    - "6"
    - "5"
    - "4"
before_install:
    - npm install typings
    - ./node_modules/.bin/typings install
before_script:
    - npm run lint
notifications:
    email: false
