language: node_js
node_js:
- '10'
- '8'
before_script:
- npm run lint
notifications:
  email: false
deploy:
  provider: npm
  email: 39.nuko@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: nukosuke/annict.js
